### ISSUE TITLE
Undefined behavior involving shifts of negative numbers

### ISSUE THREAD

**Issue by pixelspark** [vzsg/ed25519#1]
Hi Zsolt! First of all thanks for the great work. Library's been very helpful. Now when compiling it under clang with the undefined behavior sanitizer on, I get messages about left shifts of signed (negative) integers being undefined. As there are a lots of them, I cannot really use the sanitizer anymore to find undefined behavior in my own code 🙂 

Also it seems to be a good idea to fix this anyway (even though the code is working fine!). See this  https://github.com/jedisct1/libsodium/issues/333 for a more detailed discussion (same issue occured in libsodium) and why it's good to fix it.

Could you have a look into this? Perhaps it is as simple as importing a new version of the upstream code.

**Comment by vzsg** [comment]
Hi @pixelspark and thanks for the report!

Unfortunately the upstream library hasn't been updated in 6 months (2 months older than my copy), and is also affected. I will take a stab at fixing the issue here first, using the libsodium discussion and PRs as the base.

**Comment by vzsg** [comment]
I took some ideas from the libsodium discussion for some mechanical changes to the problematic shifts – in Xcode, the isses went away while running the tests in the project.

I have tagged 0.1.1-beta.1 on the PR's branch, can you please test if this clears up the sanitizer's errors on your side, and if your project is still working correctly?
